pipeline  
{
    agent 
    {
        label 'docker'
    }
    stages 
    {
        stage('Clone') 
        {
            steps 
            {
                git branch: 'main', url: 'http://192.168.56.102:3000/vdimitrov/supercalc'
            }
        }
        stage('Build')
        {
            steps
            {
                sh 'docker image build -t img-web .'
            }
        }
        stage('Run')
        {
            steps
            {
                sh 'docker container rm -f con-web || true'
                sh 'docker container run -d -p 8000:80 --net app-net --name con-web img-web'

            }
        }
        stage('CleanUp')
        {
            steps
            {
                cleanWs()
            }
        }
    }
}